export { default as AcademicTermsManagement } from './AcademicTermsManagement.jsx';
export { default as AcademicYearsManagement } from './AcademicYearsManagement.jsx';
export { default as ClassLevelsManagement } from './ClassLevelsManagement.jsx';
export { default as ExamManagement } from './ExamManagement.jsx';
export { default as ProgramManagement } from './ProgramsManagement.jsx';
export { default as StudentManagement } from './StudentsManagement.jsx';
export { default as SubjectManagement } from './SubjectManagement.jsx';
export { default as TeacherManagement } from './TeacherManagement.jsx';
export { default as YearGroupManagement } from './YearGroupsManagement.jsx';